// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByqUjWEjHUreVcr13ubVh5dwftKeEKEc0',
    appId: '1:446377015997:web:b9d465070390b0904055d4',
    messagingSenderId: '446377015997',
    projectId: 'login-2b77f',
    authDomain: 'login-2b77f.firebaseapp.com',
    storageBucket: 'login-2b77f.appspot.com',
    measurementId: 'G-EZEG1QQ4PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7BFYC34E1yR8nv7IEwMX_sprH--P2leA',
    appId: '1:446377015997:android:d88b29dfa14d38834055d4',
    messagingSenderId: '446377015997',
    projectId: 'login-2b77f',
    storageBucket: 'login-2b77f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQYJJgI_JBKktLhE4JrYSXAaDJCYxv9BA',
    appId: '1:446377015997:ios:b00791e8ddf399cc4055d4',
    messagingSenderId: '446377015997',
    projectId: 'login-2b77f',
    storageBucket: 'login-2b77f.appspot.com',
    androidClientId: '446377015997-dhikh7jh3bkjgdo7264v8cqf2ahddh1g.apps.googleusercontent.com',
    iosClientId: '446377015997-8n4a7bf3gtc2k03gpkepe1ah8rujvqte.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQYJJgI_JBKktLhE4JrYSXAaDJCYxv9BA',
    appId: '1:446377015997:ios:b00791e8ddf399cc4055d4',
    messagingSenderId: '446377015997',
    projectId: 'login-2b77f',
    storageBucket: 'login-2b77f.appspot.com',
    androidClientId: '446377015997-dhikh7jh3bkjgdo7264v8cqf2ahddh1g.apps.googleusercontent.com',
    iosClientId: '446377015997-8n4a7bf3gtc2k03gpkepe1ah8rujvqte.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication13',
  );
}
